sudo: required

install:
  - curl -sSL https://get.docker.com/ | sudo sh
  - sudo pip install docker-compose
  - pwd
  - ls -lah

before_script:
  - cd ../
  - wget https://github.com/ArroyoLabs/erdiko/archive/develop.zip
  - unzip develop.zip
  - mv erdiko-develop erdiko
  - ls -lah

script:
  - cd erdiko
  - ls -lah
  - sudo docker-compose up -d
  - sudo docker-compose ps
  - ln -s ../erdiko-core/scripts scripts
  - sudo chmod 770 scripts/*.sh
  - sudo docker exec erdiko_php7 /code/scripts/ci-setup.sh
  - ln -s erdiko-core erdiko/vendor/erdiko/core
  - sudo docker exec erdiko_php7 /code/scripts/ci-tests.sh

notifications:
  email:
    - john@arroyolabs.com 
